### ISSUE TITLE
Outbound connection setting "linger" is invalid, and often "CHANNEL_HANGUP_COMPLETE" or other events are not received

### ISSUE THREAD

**Issue by luoyumin** [percipia/eslgo#26]
**Problem**
    Outbound connection setting "linger" is invalid, the connection is immediately disconnected after hanging up, resulting in no event received.
    As a result, the agent status cannot be properly monitored through "esl"

**Comment by zenthangplus** [comment]
any update for this issue?

**Comment by luoyumin** [comment]
Thank you for your attention. You can check out the latest mergers
