### ISSUE TITLE
HI, I would like to confirm something about the setting of origination_uuid

### ISSUE THREAD

**Issue by chenzhcnj** [percipia/eslgo#28]
HI, I would like to confirm something about the setting of origination_uuid
![K28(U12YPR4~G @9N@TFCC](https://github.com/percipia/eslgo/assets/42004903/1eccb93b-1342-4227-b931-75262c82bb76)

Why is origination_uuid excluded when executing OriginateCall?

**Comment by shambles07** [comment]
These resources may help:
* https://stackoverflow.com/questions/62872061/why-am-i-getting-duplicate-uuid-when-using-api-create-uuid
* https://developer.signalwire.com/freeswitch/Channel-Variables-Catalog/origination_uuid_16353330/
