### ISSUE TITLE
It doesn't exit on wrong password

### ISSUE THREAD

**Issue by egorsmkv** [percipia/eslgo#5]
Hello!

Thanks for the library, @winsock ! It's so useful and helpful!

I've encountered this behavior: when I set an incorrect ESL password the library replies like the following:

```
$ ~/go/bin/go run ~/main.go

2021/02/16 13:43:36 Failed to auth &{%!e(string=failed to auth Content-Type: []string{"command/reply"}
Reply-Text: []string{"-ERR invalid"}
)}
2021/02/16 13:43:41 No one to handle response Content-Type: []string{"text/disconnect-notice"}
Content-Length: []string{"67"}
Disconnected, goodbye.
See you at ClueCon! http://www.cluecon.com/
```

and it never exits. 

In my opinion, the program must exit after sending "exit" command to FreeSWITCH instance.

**Comment by winsock** [comment]
Hi @egorsmkv thanks for the bug report!

I believe I see the issue in the library, I do not return the error in Dial if authentication is unsuccessful. 

I will fix this oversight shortly and test this error condition to ensure it's working properly.

**Comment by egorsmkv** [comment]
Thanks, I wait to test it as well.

**Comment by winsock** [comment]
@egorsmkv I have created what should fix this issue in #6 I have also created a release candidate tag for easier testing by yourself. You can switch to `v1.3.3-rc` to verify if it is working as expected.

I personally used this example to confirm things are working as intended:
https://github.com/percipia/eslgo/blob/close_fix/example/events/events.go

**Comment by egorsmkv** [comment]
Now, it closes as intented but now I am getting a randomized panic:

```
INFO[0003] Inbound Connection Disconnected              
ERRO[0010] failed to auth Content-Type: []string{"command/reply"}
Reply-Text: []string{"-ERR invalid"} 
panic: send on closed channel

goroutine 16 [running]:
github.com/percipia/eslgo.(*Conn).receiveLoop(0xc000090a20)
	/root/gopath/pkg/mod/github.com/percipia/eslgo@v1.3.3-rc/connection.go:250 +0x299
created by github.com/percipia/eslgo.newConnection
	/root/gopath/pkg/mod/github.com/percipia/eslgo@v1.3.3-rc/connection.go:67 +0x53a

```

**Comment by winsock** [comment]
@egorsmkv It looks like this uncovered an underlying issue that wasn't shown due to the connection never exiting. I have pushed `1.3.3-rc2` that resolves this panic.

**Comment by egorsmkv** [comment]
It seems the issue is still here:

```
INFO[0019] Inbound Connection Disconnected              
ERRO[0022] failed to auth Reply-Text: []string{"-ERR invalid"}
Content-Type: []string{"command/reply"} 
panic: send on closed channel

goroutine 53 [running]:
github.com/percipia/eslgo.(*Conn).receiveLoop(0xc000158240)
	/root/gopath/pkg/mod/github.com/percipia/eslgo@v1.3.3-rc2/connection.go:252 +0x2b9
created by github.com/percipia/eslgo.newConnection
	/root/gopath/pkg/mod/github.com/percipia/eslgo@v1.3.3-rc2/connection.go:67 +0x53a
```

**Comment by winsock** [comment]
Hi @egorsmkv 

I resolved the race condition being caused by the early shutdown due to auth. Thank you for finding it, I'm sure we would've been bitten by it at some point in the future. Can you try `1.3.3-rc3` to verify that the issue is indeed gone for good this time?

**Comment by egorsmkv** [comment]
Now it properly works! Thank you, Andrew!

I just noticed that when the connection is closing here appears this error:

```
Error receiving message read tcp 127.0.0.1:50022->127.0.0.1:8021: use of closed network connection
```

and thisL

```
Failed to auth &{%!e(string=write) %!e(string=tcp) %!e(*net.TCPAddr=&{[127 0 0 1] 50026 }) %!e(*net.TCPAddr=&{[127 0 0 1] 8021 }) %!e(*errors.errorString=&{use of closed network connection})}
```

Is this normal?

**Comment by winsock** [comment]
I'm glad to hear it! Thank you for raising the issue!

Those messages are normal around the shutdown of the connection. They are printed to the log just in case to help trace if there are any issues. I could potentially add in an option to either redirect the logging messages to a supplied logger or to quiet the internal library logs messages. 

You can see where they happen here:
https://github.com/percipia/eslgo/blob/close_fix/connection.go#L243
https://github.com/percipia/eslgo/blob/close_fix/inbound.go#L68

**Comment by egorsmkv** [comment]
Yes, the ability to set own logger would be so useful!

I am using logrus inside my project so I can suppress these messages by setting the logging level.

**Comment by winsock** [comment]
I will open another issue tracking this feature request and I will get it added in for the next release. Thanks @egorsmkv!
